---
title: "And We're off and Blogging!"
description: |
  Welcome my Blog - detailing all things in the life of a PhD statistics
  student at CMU
author:
  - name: Shamindra Shrotriya
    url: https://www.shamindras.com/
date: 12-26-2018
output:
  radix::radix_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(emo) # For emoji's
```

## Welcome - Let's Get Statistical!

Hi there! I'm Shamindra and a graduate student in Statistics at the wonderful Carnegie Mellon University (Go Tartans!). I've decided to start blogging to document my learning and development in
statistics as a new graduate student. 

I'd like it to be a fun place to document interesting things I like to read about in the statistics and machine learning space  (`rstats`, `python`, `theory`...)  as well as anything else I am into e.g. books, cricket (the Australian version of baseball) etc.

Feel free to pull up a chair and join me so that we can explore together!

## Credits

The credit to starting this blog goes to the following people from the interweb
who stopped me from procrastinating (most of whom I have not met in person `r emo::ji("smile")`). I
hope to not disappoint and create some useful content here `r emo::ji("vulcan_salute")`.

- [Yihui Xie](https://yihui.name/), [JJ Allaire](https://github.com/jjallaire) and [Rich Iannone](https://twitter.com/riannone)- For co-developing the fantastic `radix` package which upon which this blog/ site is based
- [Mara Averick](https://twitter.com/dataandme) for posting really useful blogdown links to get me started creating my own blog
- [Rachel Thomas](http://www.fast.ai/) for posting this [fantastic blog post](http://www.fast.ai/2017/04/06/alternatives/) encouraging people like me to (finally!) create a blog.




